include(FindPackageHandleStandardArgs)

find_path(ROQ_LOGGING_INCLUDE_DIR "roq/logging.h")

find_library(ROQ_LOGGING_LIBRARY NAMES roq-logging)

find_package_handle_standard_args(ROQ_LOGGING
  FOUND_VAR
    ROQ_LOGGING_FOUND
  REQUIRED_VARS
    ROQ_LOGGING_LIBRARY
    ROQ_LOGGING_INCLUDE_DIR
)

set(ROQ_LOGGING_INCLUDE_DIRS "${ROQ_LOGGING_INCLUDE_DIR}")

set(ROQ_LOGGING_LIBRARIES "${ROQ_LOGGING_LIBRARY}")
