include(FindPackageHandleStandardArgs)

find_path(CLICKHOUSE_CPP_INCLUDE_DIR clickhouse/client.h)

find_library(CLICKHOUSE_CPP_LIBRARY NAMES clickhouse-cpp-lib)

find_package_handle_standard_args(
  ClickHouse_CPP
  FOUND_VAR CLICKHOUSE_CPP_FOUND
  REQUIRED_VARS CLICKHOUSE_CPP_LIBRARY CLICKHOUSE_CPP_INCLUDE_DIR)

set(CLICKHOUSE_CPP_INCLUDE_DIRS ${CLICKHOUSE_CPP_INCLUDE_DIR})

set(CLICKHOUSE_CPP_LIBRARIES ${CLICKHOUSE_CPP_LIBRARY})
